name: CI/CD for Spring Boot with Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Secrets
        run: |
         if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
         echo "DOCKER_USERNAME is empty"
         exit 1
         else
         echo "DOCKER_USERNAME is set"
         fi
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK environment
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build the Spring Boot application
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t janggon/javame-trans-service:latest .
          docker push janggon/javame-trans-service:latest

      # Deploy the application using Docker-Compose
      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            port: 8822
            key: ${{ secrets.PRIVATE_KEY }}
            script: |
              cd /home/aiot2/aiot2-team3/docker
              docker-compose pull javame-trans-service
              docker-compose down javame-trans-service
              docker-compose up -d javame-trans-service
