name: CI/CD for Spring Boot with Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Secrets
        run: |
         if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
         echo "DOCKER_USERNAME is empty"
         exit 1
         else
         echo "DOCKER_USERNAME is set"
         fi
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK environment
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build the Spring Boot application
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t janggon/javame-trans-service:latest .
          docker push janggon/javame-trans-service:latest

      # Deploy the application using Docker-Compose
      - name: Deploy with Docker-Compose
        run: |
          ssh -o StrictHostKeyChecking=no -p 8822 ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
            cd /home/aiot2/aiot2-team3/docker
            docker-compose pull
            docker-compose up -d
          EOF
